import test from 'node:test';
import assert from 'node:assert/strict';
import {
  isDueForReevaluation, resolveCandidateMetric, reevaluateCandidate, buildCandidateUpdate, runReevaluation, parseArgs,
} from '../scripts/reevaluatePromises.js';

/**
 * reevaluatePromises.test.js
 * ===========================
 * The scheduled re-evaluation job: which records are due, that a found actual
 * is judged with the fixed rules, that a failed or non-comparable lookup is
 * INSUFFICIENT_EVIDENCE with a reason (never a substituted value), that an
 * ACCEPTED (human-reviewed) record only ever gets a proposal, and that a run
 * is bounded, scoped and repeatable. No database or network: the store and
 * the outcome lookup are in-memory fakes.
 */

const AS_OF = new Date('2026-10-02T00:00:00Z');

// Shape of a real PromiseCandidate generated by PromiseExtractionService.buildPromiseCandidate.
const candidate = (overrides = {}) => ({
  _id: overrides.id || 'TCS-FY2025-CAND-001',
  id: 'TCS-FY2025-CAND-001',
  symbol: 'TCS',
  dataMode: 'CURATED_VERIFIED',
  reviewStatus: 'PENDING_REVIEW',
  ...overrides,
  promise: {
    statement: 'We will keep operating margin at or above 26% for FY2025.',
    originalExcerpt: 'we will keep operating margin at or above 26%',
    category: 'MARGIN', promiseDate: '2024-04-12', targetPeriod: 'FY2025', targetType: 'PERCENTAGE',
    targetValue: 26, targetUnit: 'PERCENT', operator: 'AT_LEAST', metric: 'EBITDA_MARGIN',
    ...(overrides.promise || {}),
  },
  outcome: { status: 'PENDING', actualValue: null, actualUnit: null, evaluationDate: null, explanation: null, ...(overrides.outcome || {}) },
  promiseEvidence: {
    sourceTitle: 'Transcript of the Q4 FY2024 Earnings Conference Call', sourceType: 'EARNINGS_TRANSCRIPT',
    sourceUrl: 'https://www.bseindia.com/xml-data/corpfiling/Attachhis/example-q4fy24.pdf', publishedAt: '2024-04-12', pageNumber: 5,
    excerpt: 'we will keep operating margin at or above 26%',
  },
  outcomeEvidence: null,
  verification: { verifiedAt: '2026-09-01', verifiedBy: 'AUTOMATED_CANDIDATE_GENERATOR', evidenceConfidence: 0.5, notes: null },
});

// Shape returned by OutcomeEvidenceService.searchActualOutcomesLocalFirst (tier a, CompanyHistoricalFact).
const factMatch = (actualValue, extra = {}) => ({
  actualValue, actualUnit: 'PERCENTAGE', actualPeriod: 'FY2025',
  outcomeStatement: `FY2025 results: ${actualValue} PERCENTAGE for FY2025.`,
  outcomeSource: 'Press Release: Q4 FY2025 Financial Results',
  outcomeSourceUrl: 'https://nsearchives.nseindia.com/corporate/TCS_example_PressRelease.pdf',
  outcomeSourceDate: '2025-04-10', evidenceType: 'DOCUMENT_EVIDENCE', provider: 'company-historical-fact', confidence: 0.85,
  ...extra,
});

test('due selection: open outcome + closed period + reporting window passed; never REJECTED; a human INSUFFICIENT_EVIDENCE is left alone', () => {
  assert.equal(isDueForReevaluation(candidate(), { asOf: AS_OF }), true);
  assert.equal(isDueForReevaluation(candidate({ promise: { targetPeriod: 'FY2027' } }), { asOf: AS_OF }), false);
  assert.equal(isDueForReevaluation(candidate(), { asOf: new Date('2025-05-15T00:00:00Z') }), false, 'inside the 60-day reporting window');
  assert.equal(isDueForReevaluation(candidate({ reviewStatus: 'REJECTED' }), { asOf: AS_OF }), false);
  assert.equal(isDueForReevaluation(candidate({ outcome: { status: 'MISSED' } }), { asOf: AS_OF }), false);
  assert.equal(isDueForReevaluation(candidate({ outcome: { status: 'INSUFFICIENT_EVIDENCE' } }), { asOf: AS_OF }), false);
  assert.equal(isDueForReevaluation(candidate({ outcome: { status: 'INSUFFICIENT_EVIDENCE' }, reevaluation: { lastRunAt: new Date('2026-09-25') } }), { asOf: AS_OF }), true);
});

test('metric resolution never guesses: stored metric first, then only unambiguous categories', () => {
  assert.equal(resolveCandidateMetric(candidate()), 'EBITDA_MARGIN');
  assert.equal(resolveCandidateMetric(candidate({ promise: { metric: null, category: 'PROFITABILITY' } })), 'PAT');
  assert.equal(resolveCandidateMetric(candidate({ promise: { metric: null, category: 'ORDER_BOOK' } })), null);
  assert.equal(resolveCandidateMetric(candidate({ promise: { metric: null, category: 'OTHER' } })), null);
});

test('a found actual below the floor is MISSED (not partial) and is applied to a PENDING_REVIEW candidate after validation', async () => {
  const calls = [];
  const evaluation = await reevaluateCandidate(candidate(), {
    profile: { symbol: 'TCS' }, asOf: AS_OF, outcomeSearchFn: async (profile, promise) => { calls.push(promise); return factMatch(25); },
  });
  assert.equal(calls[0].targetUnit, 'PERCENTAGE', 'curated PERCENT is passed in the unit vocabulary the matcher normalizes');
  assert.equal(calls[0].metric, 'EBITDA_MARGIN');
  assert.equal(evaluation.result, 'MISSED');
  assert.equal(evaluation.outcome.status, 'MISSED');
  assert.equal(evaluation.outcome.actualValue, 25);
  assert.match(evaluation.outcome.explanation, /MISSED/);
  const update = buildCandidateUpdate(candidate(), evaluation, { asOf: AS_OF, runId: 'run-1' });
  assert.equal(update.applied, true);
  assert.equal(update.$set.outcome.status, 'MISSED');
  assert.equal(update.$set.outcomeEvidence.sourceUrl, factMatch(25).outcomeSourceUrl);
  assert.equal(update.$set.reevaluation.appliedToOutcome, true);

  const exceeded = await reevaluateCandidate(candidate(), { profile: { symbol: 'TCS' }, asOf: AS_OF, outcomeSearchFn: async () => factMatch(29) });
  assert.equal(exceeded.outcome.status, 'EXCEEDED', 'EXCEEDED is now its own stored status');
});

test('a provider failure during the actual lookup yields INSUFFICIENT_EVIDENCE with the specific reason and no substituted value', async () => {
  const evaluation = await reevaluateCandidate(candidate(), {
    profile: { symbol: 'TCS' }, asOf: AS_OF, outcomeSearchFn: async () => { throw new Error('IndianAPI 429 Too Many Requests'); },
  });
  assert.equal(evaluation.result, 'INSUFFICIENT_EVIDENCE');
  assert.match(evaluation.reason, /lookup failed \(IndianAPI 429 Too Many Requests\)/);
  assert.equal(evaluation.outcome.actualValue, null);
  assert.equal(evaluation.outcomeEvidence, null);
  const noMatch = await reevaluateCandidate(candidate(), { profile: { symbol: 'TCS' }, asOf: AS_OF, outcomeSearchFn: async () => null });
  assert.equal(noMatch.result, 'INSUFFICIENT_EVIDENCE');
  assert.match(noMatch.reason, /no verified actual result has been matched/);
});

test('a quarterly actual returned for an annual target is INSUFFICIENT_EVIDENCE, never compared', async () => {
  const evaluation = await reevaluateCandidate(candidate(), { profile: { symbol: 'TCS' }, asOf: AS_OF, outcomeSearchFn: async () => factMatch(27, { actualPeriod: 'Q4 FY2025' }) });
  assert.equal(evaluation.result, 'INSUFFICIENT_EVIDENCE');
  assert.match(evaluation.reason, /granularity mismatch/);
  assert.equal(evaluation.outcome.actualValue, null);
});

test('an ACCEPTED candidate only receives a proposal; its human-reviewed outcome is never overwritten', async () => {
  const accepted = candidate({ reviewStatus: 'ACCEPTED' });
  const evaluation = await reevaluateCandidate(accepted, { profile: { symbol: 'TCS' }, asOf: AS_OF, outcomeSearchFn: async () => factMatch(27) });
  const update = buildCandidateUpdate(accepted, evaluation, { asOf: AS_OF });
  assert.equal(update.applied, false);
  assert.ok(!('outcome' in update.$set));
  assert.equal(update.$set.reevaluation.proposedOutcome.status, 'ACHIEVED');
  assert.equal(update.$set.reevaluation.appliedToOutcome, false);
});

test('a run is scoped by symbol, bounded by batch size, writes nothing on a dry run, and is repeatable', async () => {
  const store = new Map([
    candidate({ id: 'TCS-FY2025-CAND-001' }),
    candidate({ id: 'TCS-FY2025-CAND-002', promise: { metric: 'PAT', category: 'PROFITABILITY', targetType: 'ABSOLUTE', targetValue: 45000, targetUnit: 'INR_CRORE' } }),
    candidate({ id: 'TCS-FY2027-CAND-001', promise: { targetPeriod: 'FY2027' } }),
    candidate({ id: 'INFY-FY2025-CAND-001', symbol: 'INFY' }),
  ].map((c) => [c.id, c]));
  const findCandidatesFn = async ({ symbols }) => [...store.values()].filter((c) => !symbols || symbols.includes(c.symbol)).map((c) => structuredClone(c));
  const writes = [];
  const updateCandidateFn = async (c, $set) => {
    writes.push(c.id);
    const current = store.get(c.id);
    store.set(c.id, { ...current, ...('outcome' in $set ? { outcome: $set.outcome, outcomeEvidence: $set.outcomeEvidence } : {}), reevaluation: $set.reevaluation });
  };
  const outcomeSearchFn = async (profile, promise) => (promise.metric === 'PAT'
    ? { ...factMatch(48000), actualUnit: 'INR_CRORE' }
    : factMatch(25));

  const dry = await runReevaluation({ findCandidatesFn, updateCandidateFn, outcomeSearchFn, symbols: ['TCS'], asOf: AS_OF, dryRun: true });
  assert.equal(dry.due, 2, 'FY2027 is not due and INFY is out of scope');
  assert.equal(writes.length, 0);

  const bounded = await runReevaluation({ findCandidatesFn, updateCandidateFn, outcomeSearchFn, symbols: ['TCS'], asOf: AS_OF, batchSize: 1 });
  assert.equal(bounded.processed, 1);
  assert.equal(writes.length, 1);

  const rest = await runReevaluation({ findCandidatesFn, updateCandidateFn, outcomeSearchFn, symbols: ['TCS'], asOf: AS_OF });
  assert.equal(rest.processed, 1, 'the resolved record is no longer due; the remaining one is picked up');
  assert.equal(store.get('TCS-FY2025-CAND-001').outcome.status, 'MISSED');
  assert.equal(store.get('TCS-FY2025-CAND-002').outcome.status, 'ACHIEVED');
  assert.equal(store.get('INFY-FY2025-CAND-001').outcome.status, 'PENDING', 'never touched outside --symbol scope');

  const again = await runReevaluation({ findCandidatesFn, updateCandidateFn, outcomeSearchFn, symbols: ['TCS'], asOf: AS_OF });
  assert.equal(again.due, 0, 'safe to re-run: nothing left to do');
});

test('CLI arguments accept --symbol=X, --symbol X and --symbols A,B', () => {
  assert.deepEqual(parseArgs(['--symbol=tcs']).symbols, ['TCS']);
  assert.deepEqual(parseArgs(['--symbol', 'INFY']).symbols, ['INFY']);
  assert.deepEqual(parseArgs(['--symbols', 'TCS,INFY,HDFCBANK', '--expect-target', 'h/db']).symbols, ['TCS', 'INFY', 'HDFCBANK']);
  assert.equal(parseArgs([]).symbols, null);
  assert.equal(parseArgs(['--dry-run']).dryRun, true);
});
